name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
#these are free variables from Azure
#https://learn.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml
trigger: none

#any variables you want to later define in your pipeline, can define here

parameters:
  - name: PythonVersion
    type: string
    values:
      - 3.9
      - 3.10
      - 3.11
    default: 3.11

#here each hyphon represents a new parameter, so here we have 1

pool: #of agents
  vmImage: windows-latest

steps:
  - checkout: self #will check repository in which it is

  - task: UsePythonVersion@0
    displayName: "Use Python"
    inputs:
      versionSpec: ${{ parameters.PythonVersion }}

  - script: | # this allows you to do multiple lines
      pip install -r requirements.txt
      pytest --junitxml=TEST-shiftleft.xml
    workingDirectory: tests/ci #this tells you where to go
    displayName: "Run the CI tests"

  - task: PublishTestResults@2
    displayName: "Publish Test Results **/TEST-**.xml"
    inputs:
      searchFolder: tests/ci
      failTaskOnFailedTests: true
    condition: always() #this will allow it to run even if fails

